apiVersion: jaegertracing.io/v1
kind: Jaeger

metadata:
  name: jaeger
  namespace: monitoring

spec:
  strategy: allInOne
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-master:9200
