apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: foo
  labels:
    app: foo

spec:
  selector:
    matchLabels:
      app: foo
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: { duration: 1m }
        - setWeight: 60
        - pause: { duration: 1m }
        - setWeight: 80
        - pause: { duration: 1m }
  template:
    metadata:
      labels:
        app: foo
      annotations: {}
    spec:
      serviceAccountName: foo
      containers:
        - name: foo
          image: "joaofnds/foo:0.1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: CONFIG_PATH
              value: "/etc/config"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: "/etc/config"
              name: config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: foo-prod-config
