apiVersion: apps/v1
kind: Deployment

metadata:
  name: foo
  labels:
    app: foo

spec:
  selector:
    matchLabels:
      app: foo
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: foo
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "postgres-postgresql:5432"
        "vault.hashicorp.com/agent-inject": "true"
        "vault.hashicorp.com/agent-inject-secret-postgres": "foo/postgres"
        "vault.hashicorp.com/agent-inject-template-postgres": |
          {{- with secret "foo/postgres" -}}
          postgres:
            host: localhost
            port: 5432
            username: {{ .Data.data.username }}
            password: {{ .Data.data.password }}
            database: foo
          {{- end }}
        "vault.hashicorp.com/role": "foo"
    spec:
      serviceAccountName: foo
      containers:
        - name: foo
          image: "joaofnds/foo:0.0.5"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: CONFIG_PATH
              value: "/vault/secrets/"
            - name: CONFIG_NAME
              value: postgres
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
