apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: foo
  labels:
    app: foo

spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
      annotations: {}
    spec:
      serviceAccountName: foo
      containers:
        - name: foo
          image: "joaofnds/foo:0.1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: CONFIG_PATH
              value: "/etc/config"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: "/etc/config"
              name: config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: foo-prod-config
  strategy:
    canary:
      canaryService: foo-canary
      stableService: foo-stable
      trafficRouting:
        istio:
          virtualService:
            name: foo
            routes:
              - primary
          destinationRule:
            name: foo
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause:
            duration: 1m
        - setWeight: 60
        - pause:
            duration: 1m
        - setWeight: 80
        - pause:
            duration: 1m
