apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler

metadata:
  name: foo
  namespace: foo-prod

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foo
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
