apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: foo-config
  namespace: foo
spec:
  encryptedData:
    config.yaml: AgAR3fcHkdQ3RG40Acy72zurPE7maWRE9+PYUT3meI5sXhJnk8Cb2cSbR18w5tGzcV0xwFQZjFTQkfmT8tBimQjX1E7pEnqrOeq8Wh8XcS9F9XzrRoWPv1elKSIgnTmn+Pxn5U0mkAP2wo6U/r+/TwtXqwLeLQCvhwjx98WN7e4QNIbQCxHevZZ6lOiAyxgJCfLV7pwG9V3OYJBUNzbPXvbEJHkdkCKD7AE14c9MNS/rbmhZH89/7NfSWsVsJ5d9fqeM5TYaFuNrkqvCNJj/+UywYdVDWSUzZvU8Tlylmwg7V8+/Pq8gENgBZxxXtuvCZ6m0moXXJ+kpSIDW0t1HHA6cvlPuMG5PvZz/tUERZ+HA/fsIo1N4hWFOBui0dG4sQuYENfzBg2WsthopZogRJvaqmSuDLz8CgEudodGnT+LMS5rPeAJiZLE91ZJo6ftD56J5vW5FbtFkxshnwbjPpxAEL3BHMv9wZDPPGkU8evpo7bEjW3Y6pQjvJMTwiDhmProu+AknXVwtaMZ9mmRV9cTZjLVjaEkotCGFgRYT1s7/wkw4kVAXmaUrZKCi10InvQcIsPApHdmDWPh/GuI0T0TKWaAUyVEeIXvT6Ifuj0DerQKSVCTmcfkyzc5eOTm9uLWuJBk6vDzkUbAfOr8D66wXki7F2Jk8QfJiG/YkFRmdIDCPTqZLDJSsc52HU4gAl7QSczeHlVmJDxOIOv7nP9xteR86jmlz86o05QKxOLvfC5Y20zuIQw7tnadgRMLU/y9GqbcwBvqtcTM9+L0p4kTtEloKPBHHxU6w9BG0vU11z2saYKY/fxa8c2iT7j0fF255VadqQAbKJRJrbny1DXOgBEs8nTSrf5YH/O9pihE29WHiSZWvixLqf5qBAq2eAbDRw+9QtWBs8GWypIWHDBvVc1pTIZAgwAM+gTclBKEc+s9bs13B3l72ePWU7GUm5kxzRsiZIwHvZR2a
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: foo-config
      namespace: foo
