apiVersion: install.istio.io/v1alpha1
kind: IstioOperator

metadata:
  name: istiocontrolplane
  namespace: istio-system

spec:
  profile: default
  meshConfig:
    defaultConfig:
      tracing:
        zipkin:
          address: "jaeger-collector.monitoring:9411"
    enablePrometheusMerge: true

values:
  global:
    proxy:
      tracer: "zipkin"
    tracer:
      zipkin:
        address: "jaeger-collector.monitoring:9411"
