apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: bar
  namespace: argocd

spec:
  project: default
  source:
    repoURL: "git@github.com:joaofnds/k8s"
    targetRevision: HEAD
    path: ./bar
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bar
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - PrunePropagationPolicy=background
