apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: bar-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://gitea.com/joao/k8s.git
    targetRevision: HEAD
    path: bar
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: bar-prod
