apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: bar

spec:
  project: default
  source:
    repoURL: "git@github.com:joaofnds/k8s"
    path: ./bar
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bar
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - PrunePropagationPolicy=background
