apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: foo-staging
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/joaofnds/foobar-infra.git
    targetRevision: HEAD
    path: ./foo-staging
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: foo-staging
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - PrunePropagationPolicy=background
