apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: foo

spec:
  project: default
  source:
    repoURL: "git@github.com:joaofnds/k8s"
    path: foo
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: foo
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
