apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: foo-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: "git@github.com:joaofnds/k8s.git"
    path: foo
    targetRevision: istio
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: foo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
