auth:
  strategy: "anonymous"

external_services:
  custom_dashboards:
    enabled: true
  grafana:
    url: "http://prometheus-grafana.monitoring.svc:3000"
  prometheus:
    auth:
      username: "admin"
      password: "admin"
    url: "http://prometheus-prometheus.monitoring.svc:9090"
